#!/bin/bash

# OG Author : Aditya Shakya (adi1090x)
rofi_command="rofi -theme power.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown=""
reboot=""
lock=""
suspend=""
logout=""
dir="$HOME/.config/rofi/power"

# Variable passed to rofi
options="$logout\n$suspend\n$lock\n$shutdown\n$reboot"

chosen="$(echo -e "$options" | $rofi_command -p "  $uptime  " -dmenu -selected-row 2)"
case $chosen in
$lock)
    xautolock -locknow
    ;;
$logout)
    awesome-client 'awesome.quit()'
    ;;
$suspend)
    systemctl suspend
    ;;
$shutdown)
    systemctl poweroff
    ;;
$reboot)
    systemctl reboot
    ;;
esac
